name: enhanced_docs_pingcap
description: Browser extension that puts wings on PingCAP Docs.
version: 2.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'
  node_interop: ^1.2.1
  over_react: ^3.12.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  sass: ^1.29.0
